### ISSUE TITLE
flash not working as intended

### ISSUE THREAD

**Issue by jsa34** [pa11y/sidekick#100]
When adding a key, for example, it should flash the public and private KP.

This USED to happen after creating a KP before the dependencies were updated, so it seems to have changed behaviour a couple of commits back...

**Comment by josebolos** [comment]
Hi @jsa34,

Thanks for creating this issue.

I'm not sure I understand what the problem is. What is the meaning of "KP"?

**Comment by jsa34** [comment]
Hello,

KP = key pair, I think (sorry been a while!)
________________________________
