### ISSUE TITLE
Ability to control access

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/sidekick#11]
We're adding a user system based on the proposal here: https://github.com/pa11y/sidekick/issues/11#issuecomment-296633552

- [x] Add a users table
- [x] Add a setup step, admin user, default permissions
- [x] Add middleware to restrict endpoint access based on user permissions
- [x] Allow users to view and regenerate their API key
- [x] Allow users to edit their email address and password
- [x] Add an admin panel to create/edit other users
- [x] ~Add API endpoints for user administration~

## Original Issue (for context)

Currently you have to take an all-or-nothing approach when hosting a dashboard. If you publicise the URL then you are allowing anyone to not only view tasks but also modify/delete them. This makes it very difficult to cater for the following use-cases:
- Sharing graphs with stakeholders/non-developers
- Publishing your site's accessibility stats
- Preventing accidental deletion
- Having a public URL for your dashboard
- Triggering test runs from a third-party service

**Comment by rowanmanning** [comment]
We've proposed adding a login system [in the proposal document](https://github.com/pa11y/sidekick/blob/master/PROPOSAL.md#outline) which should cater for these cases.

**Comment by rowanmanning** [comment]
OK here's my proposal for a user system. I'm basing this all on the following assumptions (which may not be correct):

  - **The user system should be self-contained**, no auth by third party as this would require dashboard users to go and set up API keys etc with a third party. Also what third party would we even support that wouldn't exclude _some_ people?
  - **The user system should support being disabled**, so that if you want to run Sidekick like you do with dashboard, then you can
  - **The user system should be as minimal as possible**, we shouldn't store anything that we don't absolutely need. We're not building a profile system, it's just for auth

## Database Changes

We add a new `users` table to the database, this will contain the following information:

| Field             | Type    | Notes                                                                            |
|-------------------|---------|----------------------------------------------------------------------------------|
| id                | String  | A unique identifier for the user, primary key etc                                |
| name              | String  | A human readable name for the user                                               |
| email             | String  | The email address the user logs in with (also used for notifications etc)        |
| password          | String  | A hashed password for the user                                                   |
| apiKey            | String  | A generated API key for use with the API, rather than relying on session auth    |
| permissions       | JSON    | A JSON object                                                                    |
| permissions.read  | Boolean | Whether this user has read permissions                                           |
| permissions.write | Boolean | Whether this user has write permissions. E.g. can create/edit all sites and URLs |
| permissions.admin | Boolean | Whether the user can create/edit users                                           |

The permissions are kept simple and global. If you have write access, you have write access to _everything_. Similarly admin access grants you the ability to edit all users.

I'm also proposing that we include two default users:

  1. A super-admin user named `admin` or similar. It will be impossible through the UI to delete this user or change their permissions. On first run of Sidekick, this user would be set up
  2. A user named `default` or similar. This user profile would be used for anyone who's not authenticated. By default they would have read permissions, but removing that permission would hide all results from unauthenticated users

## Front End

On the front end, I'd propose a log-in form. At first we wouldn't include forgotten password recovery in the UI but it could definitely be added in the future. In the meantime however a super admin should be able to change a user's password. In the event of a super admin forgetting their password there should be a fail-safe in manually editing the database or setting an environment variable to trigger set up again.

Persisting user sessions would be achieved with a session cookie. This session cookie would not extend to the API.

Users would have a simple profile page where they can manage their account.

I don't think there should be a sign up form – I think it's the duty of an admin to create a user (at least to start with, reducing complexity).

## API

In the API I'm proposing that write access requires an API key, which a logged in user would be able to get from their profile page. You should also be able to reset your API key in the event of it being leaked or shared somehow.

If the `default` user has read access then the read methods of the API should be accessible without authentication, mirroring the front end.

---

Let me know what you think :)

**Comment by hollsk** [comment]
* agree with leaving password recovery out for now - people will want it, especially for corporate environments, but it's something that can be easily added a later stage
* the passwords should be salted - could also add this at a later date, i guess
* agree with keeping permissions simple, but because permissions exist, people are going to ask for more complicated ones :-) so we should at least think about the ways that it can be extended in future
* ✨  I agree with everything else ✨

**Comment by andrewmee** [comment]
This all sounds sensible to me, except I would perhaps consider giving the default user write access as well.  My reasoning is that I would more usually expect sidekick to be run in an internal environment rather than exposed publicly.  Giving everyone read and write by default means that most people won't have to bother with users at all unless than actually want to lock it down, rather than having it semi-closed to start.

**Comment by rowanmanning** [comment]
@hollsk: I agree on everything you've said. And yeah salting will be there from the start.

@andrewmee: good point. What about if the setup step let you choose which permissions you wanted to be default?

**Comment by andrewmee** [comment]
Ah yeah that's a good compromise actually!
