### ISSUE TITLE
Ability to alert users when new errors occur

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/sidekick#14]
If new errors occur, it would be great to be alerted to these somehow rather than having to manually check the dashboard.

**Comment by rowanmanning** [comment]
We covered this [in the proposal document](https://github.com/pa11y/sidekick/blob/master/PROPOSAL.md#outline). Possibilities include email, Slack, IRC.

**Comment by joviano-dias** [comment]
When running pa11y in CI, say go-cd. I need my job to fail when there are errors (maybe warnings too). I run pa11y via the javascript interface and I'm contemplating using some assert mechanism to fail when errors/warnings are encountered.

I have pa11y results in JSON and this requires a bit of work detecting when there are errors. Wish pa11y could just report me back a flag if there were errors or not or run an assertion of its own ...
