### ISSUE TITLE
Ability to display a site's accessibility stats elsewhere

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/sidekick#16]
It would be great to be able to include accessibility stats somewhere on my site, or in the README of an open source project.

**Comment by rowanmanning** [comment]
Two ideas that spring to mind for me:
- Embeddable graphs (#15)
- Badges/shields

Both of these would probably require some access control (#11).

**Comment by Rayraegah** [comment]
We began exporting accessibility stats as JSON with every build of our software. In our software, we have a link to see the accessibility compliance for the current version.

When you click on it, it opens a visualization page, loads the JSON and creates a graph on the fly. 

Another thing we recently implemented was an inline, on page visual report (even in production) like
http://khan.github.io/tota11y/
