### ISSUE TITLE
Use short IDs

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/sidekick#26]
I think we should use [short IDs](https://github.com/dylang/shortid) rather than UUIDs for Page/URL/Result IDs. It'll make our endpoints more manageable/shareable.

If we do this, we'll need to:
- change the [setup migration and seed data](https://github.com/pa11y/sidekick/tree/master/data)
- probably make sure we [pass in the worker ID](https://github.com/dylang/shortid#shortidworkerinteger) whether we add clustering or not (to cater for external cluster managers)
- document that we use this in the architecture guide (probs in the database section)

**Comment by sky-jack** [comment]
This issue has now been resolved.
