### ISSUE TITLE
Trying to install PostgreSQL 9.6

### ISSUE THREAD

**Issue by FJLopezGarcia** [pa11y/sidekick#40]
Hi all,
I am trying to install PostgreSQL 9.6 in order to take a look at the new pa11y dashboard (i am new on PostgreSQL)... when i try to run "make db-create db-migrate-up" in my mac, i receive a "psql: FATAL:  password authentication failed for user "myuser"" after typing my password.

Do you know the reason? thanks a lot!!

**Comment by FJLopezGarcia** [comment]
Any update?

**Comment by rowanmanning** [comment]
Hi @FJLopezGarcia. Seems like it could be a configuration issue. Are you specifying the database connection string as [outlined in the docs](https://github.com/pa11y/sidekick#configuration)? You'll need to include the password as part of that string to run migrations.

If it's failing at the database creation stage, it might be best to try running the commands from within make individually. (See the Makefile for what these commands actually are](https://github.com/pa11y/sidekick/blob/master/Makefile#L24).

It's also worth noting that Sidekick isn't currently _functional_ – we're barely past the architectural stage so if you're expecting to be able to test URLs with it then you may be disappointed!

**Comment by andrewmee** [comment]
I've just been able to replicate this same behaviour when installing via the OSX installer.  I think it's related to that installer creating a superuser password.

If you install PostgreSQL via `brew` instead, you won't encounter this issue as no password is required.  (It may be possible/prudent to make these `make` commands work even when a password is required though).

**Comment by rowanmanning** [comment]
I've updated the documentation to reflect that `make db-create` doesn't always work. It now reads:

> Create a database. If you have the psql command on your path then you can try running the following:
> `make db-create`
> Otherwise you may have to authenticate to create the database, the SQL you need to run is:
> `CREATE DATABASE pa11y_sidekick`
