### ISSUE TITLE
Documentation for integration with Github, Gitlab...

### ISSUE THREAD

**Issue by Spone** [pa11y/sidekick#80]
Hello there,

my two cents: it would be super useful to publish, as part of the documentation, a step-by-step guide on how to integrate sidekick with the Continuous Integration features of Github and [Gitlab](https://docs.gitlab.com/ce/ci/).

By "integration", I mean "easily add accessibility testing as part of my automated tests workflow" (for instance: test my master branch periodically, test all my features branches on each code push, and publish the result of the tests in the Pull/Merge request).

Happy to discuss this with you!

Hans

**Comment by rowanmanning** [comment]
Yeah we'd definitely like to focus a lot more on documentation for Sidekick. Thanks for your input! Once we get to this point then I'll probably be in touch :)
