### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by jasonday** [pa11y/sidekick#82]
Both Pa11y & Sidekick have not seen updates in months. Inquiring on status to determine feasibility of long term use. Thanks!

**Comment by hollsk** [comment]
Hi @jasonday - both are still very much in development! We've been concentrating on Pa11y 5.x recently, to switch from PhantomJS to headless Chrome, which has required a ground-up rewrite of the core Pa11y tool. As a result, we've been holding off on major updates to Sidekick, Dashboard, etc.

Pa11y 5.x is currently in beta right now, you can check it out on the 5.x branch here https://github.com/pa11y/pa11y/tree/5.x - we'd love to get feedback on it, if you'd like to give it a try!

Once Pa11y 5 is out of beta, we'll return our attention to Sidekick :-)

Hope this helps, and thanks for using Pa11y!

**Comment by jasonday** [comment]
Thanks for the update!
