### ISSUE TITLE
Can someone post screenshots of what the dashboard looks like?

### ISSUE THREAD

**Issue by jasonday** [pa11y/sidekick#99]
In current setup, the dashboard is running and there's the ability to add sites with a minimum number of options (name, url, runnable, schedule) and after doing so, the site is saved. However, when clicking on the site, all that is showing up in the dashboard is the values of those options (no test results, etc.). Based on tickets and comments floating around here, it appears there should be more

**Comment by tombartlettmh** [comment]
I am experiencing the same issue - even after seeding the database using `make db-seed` there are no results available to view. 

This is what I see on `/sites` 
![image](https://user-images.githubusercontent.com/52742545/72608680-2708a680-391b-11ea-94d4-bb133fbd418f.png)

And this is when I click on one of the seeded sites 
![image](https://user-images.githubusercontent.com/52742545/72608729-456ea200-391b-11ea-825c-5cdbefdb0d13.png)


Does this project allow running of pa11y against the site URLs at this point? ~It feels like maybe the product isn't ready for use yet? (Hopefully I'm missing something!)~ 

EDIT: Looks like the project is in Architecture phase - see roadmap  https://github.com/pa11y/sidekick/blob/master/docs/proposal.md#roadmap

**Comment by tombartlettmh** [comment]
After looking at the Roadmap, I guess sidekick is still in "Architecture" stage? 
https://github.com/pa11y/sidekick/blob/master/docs/proposal.md#roadmap 

Apologies for not finding this before posting. I'd suggest adding some information to the readme such as "Currently not ready for public use - still in architectural phase".

**Comment by grcameron** [comment]
The readme says "Status: Architecture"

**Comment by tombartlettmh** [comment]
> The readme says "Status: Architecture"

Yep, that's fair enough. I missed it the first couple of times that's all - so I guess it's not that obvious (at least to me). But I understand that is the purpose of the status image thing.

**Comment by grcameron** [comment]
I'm also disappointed it's only in architecture phase! Would be a fantastic tool. Just starting to use the pa11y dashboard, which does the job for now. 
The status icon is quite easy to miss!

**Comment by josebolos** [comment]
Hi all,

Thanks for creating this issue. As pointed out, this project is still in the architecture phase, so it doesn't actually run any tests.

I would suggest to try to use pa11y-dashboard and pa11y-ci instead for the time being.
